### ISSUE TITLE
List in loc de ArrayList

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/course9-homework#1]
private ArrayList<String> fruitsInBasket; asta poate fi si de obicei ii de preferat sa fie List<String> chiar daca implementarea din constructor ii ArrayList. Pentru ca noi trebuie sa oferim posibilitatea de a implementa oricare din implementarile interfetei List. Daca cineva vrea sa foloseasca ca si implementare LinkedList in loc de ArrayList in momentul de fata nu poate.

**Comment by raduandreipopescu** [comment]
Ok.
In viitor, incerc sa fac ceva mai general si particularizez in implementare.
