### ISSUE TITLE
La distinctFruits

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/course9-homework#2]
Ii corect :) Frumos ca ai folosit stream-uri. Dar cum poti sa faci fara stream-uri? ( nu trebuie sa o scrii doar sa ai ideea in cap macar )

**Comment by raduandreipopescu** [comment]
Done.

public Collection<String> distinctFruits() {
        Set<String> distinctFruits = new HashSet<>();
        for (String fruit : fruitsInBasket) {
            distinctFruits.add(fruit);
        }
        return distinctFruits;
//        return fruitsInBasket.stream().distinct().collect(Collectors.toList());
    }
