### ISSUE TITLE
La Bouquet

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/course9-homework#3]
Aceasi idee ca si la ArrayList. Ii mai bine si de preferat ca tipul sa fie Set nu HashSet din aceasi cauza. Daca cineva vrea sa foloseasca TreeSet in loc de HashSet momentan nu poate deci  HashSet<String> flowersInBouquet; se transforma in Set<String> flowersInBouquet

**Comment by raduandreipopescu** [comment]
Ok.
Generalizare pentru state si particularizare la implementare.
